// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0hjgCqlxPjJPNitsnVRNeH7g5M7IURu8',
    appId: '1:98730591004:web:bad8feb17597a20fa0b0d9',
    messagingSenderId: '98730591004',
    projectId: 'tonight-tonight',
    authDomain: 'tonight-tonight.firebaseapp.com',
    storageBucket: 'tonight-tonight.appspot.com',
    measurementId: 'G-2QTQ797B2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0_MbQFy78XMQufSUNdg08H2gztVDZwbI',
    appId: '1:98730591004:android:d9da1bb19a690d27a0b0d9',
    messagingSenderId: '98730591004',
    projectId: 'tonight-tonight',
    storageBucket: 'tonight-tonight.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8f2gV9Mq14LXFYKr1DjmEmjK-Qrt3PwI',
    appId: '1:98730591004:ios:7129c18671599768a0b0d9',
    messagingSenderId: '98730591004',
    projectId: 'tonight-tonight',
    storageBucket: 'tonight-tonight.appspot.com',
    androidClientId:
        '98730591004-239hv29qt7rqdrh88bqg511uipouj9di.apps.googleusercontent.com',
    iosClientId:
        '98730591004-ae4cvqvgtj1922ro3so7dap1pftcts80.apps.googleusercontent.com',
    iosBundleId: 'com.raverteam.tonightPartners',
  );
}
