// Mocks generated by Mockito 5.2.0 from annotations
// in raver_events/test/infrastructure/firebase_event_facade_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:algolia/algolia.dart' as _i2;
import 'package:logger/src/logger.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:raver_events/domain/domain.dart' as _i5;
import 'package:raver_events/infrastructure/algolia_events_api.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeAlgoliaQuerySnapshot_0 extends _i1.Fake
    implements _i2.AlgoliaQuerySnapshot {}

class _FakeAlgolia_1 extends _i1.Fake implements _i2.Algolia {}

class _FakeAlgoliaObjectReference_2 extends _i1.Fake
    implements _i2.AlgoliaObjectReference {}

/// A class which mocks [AlgoliaEventsApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlgoliaEventsApi extends _i1.Mock implements _i3.AlgoliaEventsApi {
  MockAlgoliaEventsApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AlgoliaQuerySnapshot> getEvents(_i5.EventFilters? filters,
          _i5.SortModel? sortModel, int? pageSize, int? offset) =>
      (super.noSuchMethod(
          Invocation.method(#getEvents, [filters, sortModel, pageSize, offset]),
          returnValue: Future<_i2.AlgoliaQuerySnapshot>.value(
              _FakeAlgoliaQuerySnapshot_0())) as _i4
          .Future<_i2.AlgoliaQuerySnapshot>);
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i6.Logger {
  MockLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void v(dynamic message, [dynamic error, StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#v, [message, error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void d(dynamic message, [dynamic error, StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#d, [message, error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void i(dynamic message, [dynamic error, StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#i, [message, error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void w(dynamic message, [dynamic error, StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#w, [message, error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void e(dynamic message, [dynamic error, StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#e, [message, error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void wtf(dynamic message, [dynamic error, StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#wtf, [message, error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void log(_i6.Level? level, dynamic message,
          [dynamic error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
          Invocation.method(#log, [level, message, error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
}

/// A class which mocks [AlgoliaQuerySnapshot].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlgoliaQuerySnapshot extends _i1.Mock
    implements _i2.AlgoliaQuerySnapshot {
  MockAlgoliaQuerySnapshot() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Algolia get algolia => (super.noSuchMethod(Invocation.getter(#algolia),
      returnValue: _FakeAlgolia_1()) as _i2.Algolia);
  @override
  String get index =>
      (super.noSuchMethod(Invocation.getter(#index), returnValue: '')
          as String);
  @override
  List<_i2.AlgoliaObjectSnapshot> get hits =>
      (super.noSuchMethod(Invocation.getter(#hits),
              returnValue: <_i2.AlgoliaObjectSnapshot>[])
          as List<_i2.AlgoliaObjectSnapshot>);
  @override
  String get params =>
      (super.noSuchMethod(Invocation.getter(#params), returnValue: '')
          as String);
  @override
  String get query =>
      (super.noSuchMethod(Invocation.getter(#query), returnValue: '')
          as String);
  @override
  bool get empty =>
      (super.noSuchMethod(Invocation.getter(#empty), returnValue: false)
          as bool);
  @override
  bool get hasHits =>
      (super.noSuchMethod(Invocation.getter(#hasHits), returnValue: false)
          as bool);
  @override
  int get hitsPerPage =>
      (super.noSuchMethod(Invocation.getter(#hitsPerPage), returnValue: 0)
          as int);
  @override
  int get length =>
      (super.noSuchMethod(Invocation.getter(#length), returnValue: 0) as int);
  @override
  int get nbHits =>
      (super.noSuchMethod(Invocation.getter(#nbHits), returnValue: 0) as int);
  @override
  int get nbPages =>
      (super.noSuchMethod(Invocation.getter(#nbPages), returnValue: 0) as int);
  @override
  int get offset =>
      (super.noSuchMethod(Invocation.getter(#offset), returnValue: 0) as int);
  @override
  int get page =>
      (super.noSuchMethod(Invocation.getter(#page), returnValue: 0) as int);
  @override
  Map<String, dynamic> get facets =>
      (super.noSuchMethod(Invocation.getter(#facets),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  Map<String, dynamic> get facetsStats =>
      (super.noSuchMethod(Invocation.getter(#facetsStats),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  bool get exhaustiveNbHits =>
      (super.noSuchMethod(Invocation.getter(#exhaustiveNbHits),
          returnValue: false) as bool);
  @override
  int get processingTimeMS =>
      (super.noSuchMethod(Invocation.getter(#processingTimeMS), returnValue: 0)
          as int);
  @override
  Map<String, dynamic> toMap() =>
      (super.noSuchMethod(Invocation.method(#toMap, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  Map<String, dynamic> raw() => (super.noSuchMethod(Invocation.method(#raw, []),
      returnValue: <String, dynamic>{}) as Map<String, dynamic>);
}

/// A class which mocks [AlgoliaObjectSnapshot].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlgoliaObjectSnapshot extends _i1.Mock
    implements _i2.AlgoliaObjectSnapshot {
  MockAlgoliaObjectSnapshot() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Algolia get algolia => (super.noSuchMethod(Invocation.getter(#algolia),
      returnValue: _FakeAlgolia_1()) as _i2.Algolia);
  @override
  String get objectID =>
      (super.noSuchMethod(Invocation.getter(#objectID), returnValue: '')
          as String);
  @override
  String get index =>
      (super.noSuchMethod(Invocation.getter(#index), returnValue: '')
          as String);
  @override
  _i2.AlgoliaObjectReference get ref => (super.noSuchMethod(
          Invocation.getter(#ref),
          returnValue: _FakeAlgoliaObjectReference_2())
      as _i2.AlgoliaObjectReference);
  @override
  Map<String, dynamic> get data => (super.noSuchMethod(Invocation.getter(#data),
      returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  Map<String, dynamic> toMap() =>
      (super.noSuchMethod(Invocation.method(#toMap, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  Map<String, dynamic> raw() => (super.noSuchMethod(Invocation.method(#raw, []),
      returnValue: <String, dynamic>{}) as Map<String, dynamic>);
}
