part of 'add_event_cubit.dart';

@freezed
class AddEventState with _$AddEventState {
  const factory AddEventState({
    required Option<Club> clubInfo,
    required EventName eventName,
    required StartDateTime startDateTime,
    required EndDateTime endDateTime,
    required MinAge minAge,
    required DressCode dressCode,
    required MusicalGenres musicalGenres,
    required Description description,
    required bool isConcert,
    required ArtistName artistName,
    required bool isFacebookUrlEnabled,
    required bool isDjChannelUrlEnabled,
    required FacebookUrl facebookUrl,
    required DjChannelUrl djChannelUrl,
    required List<TicketPool> ticketPools,
    required EventPhoto eventPhoto,
    required FormzStatus status,
    required AddEventStep currentStep,
    required bool isSubmitEnabled,
    required Option<String> errorMessage,
    required CubitStatus discountsStatus,
    required List<CollectedDiscount> availableDiscounts,
    required bool isExclusiveEvent,
    required bool isDiscountApplied,
    required Option<CollectedDiscount> appliedDiscount,
    required Option<double> eventFee,
  }) = _AddEventState;

  factory AddEventState.initial() => AddEventState(
        clubInfo: none(),
        eventName: const EventName.pure(),
        startDateTime: const StartDateTime.pure(),
        endDateTime: const EndDateTime.pure(),
        minAge: const MinAge.pure(),
        dressCode: const DressCode.pure(),
        musicalGenres: const MusicalGenres.pure(),
        description: const Description.pure(),
        isConcert: false,
        artistName: const ArtistName.pure(),
        isFacebookUrlEnabled: false,
        isDjChannelUrlEnabled: false,
        facebookUrl: const FacebookUrl.pure(),
        djChannelUrl: const DjChannelUrl.pure(),
        ticketPools: [],
        eventPhoto: const EventPhoto.pure(),
        status: FormzStatus.pure,
        currentStep: AddEventStep.nameAndDesc,
        isSubmitEnabled: false,
        errorMessage: none(),
        discountsStatus: CubitStatus.initial,
        availableDiscounts: [],
        appliedDiscount: none(),
        isDiscountApplied: false,
        isExclusiveEvent: false,
        eventFee: none(),
      );
}
