// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0_MbQFy78XMQufSUNdg08H2gztVDZwbI',
    appId: '1:98730591004:android:7e99e2d387252529a0b0d9',
    messagingSenderId: '98730591004',
    projectId: 'tonight-raver',
    storageBucket: 'tonight-raver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmvF9K97hBs2puGQQONicvndvHU9wSTDk',
    appId: '1:98730591004:ios:9d1e77b1370d5201a0b0d9',
    messagingSenderId: '98730591004',
    projectId: 'tonight-raver',
    storageBucket: 'tonight-raver.appspot.com',
    androidClientId: '98730591004-gaapuj74vv6np0q7i9f9tmhfqbg783ba.apps.googleusercontent.com',
    iosClientId: '98730591004-loojab9i15qtlab8kgknc3ebpajgf4gf.apps.googleusercontent.com',
    iosBundleId: 'com.raverteam.tonightScanner',
  );
}
