// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:raver_partners/env_keys.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env[androidApiKey]!,
    appId: '1:133839090627:android:2e7174f5fb9863d2e1c376',
    messagingSenderId: '133839090627',
    projectId: 'raver-1fec4',
    storageBucket: 'raver-1fec4.appspot.com',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env[iosApiKey]!,
    appId: '1:133839090627:ios:bf177468b6d665ebe1c376',
    messagingSenderId: '133839090627',
    projectId: 'raver-1fec4',
    storageBucket: 'raver-1fec4.appspot.com',
    androidClientId: '133839090627-3vrcaoj7s27mteo7crlb86ugd52h1l16.apps.googleusercontent.com',
    iosClientId: '133839090627-up1mvkhu78ac1au2atccoorp2t7uop8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.raver.partners',
  );
}
