default_platform(:ios)

platform :ios do
    lane :deploy_to_testflight do
        build_flutter_app()
        deploy_flutter_app()
    end

    lane :promote_to_app_store do
        api_key = app_store_connect_api_key(
            key_id: "#{ENV['APP_STORE_CONNECT_KEY_ID']}",
            issuer_id: "#{ENV['APP_STORE_CONNECT_ISSUER_ID']}",
            key_content: "#{ENV['APP_STORE_CONNECT_API_KEY']}",
            is_key_content_base64: true
        )
        app_store_connect_api_key(api_key: api_key)
        deliver(api_key: api_key, submit_for_review: true)
    end

    private_lane :build_flutter_app do
        sh("flutter", "clean")
        sh("flutter", "pub", "get")
        sh("flutter", "build", "ipa", "--release")
    end

    private_lane :deploy_flutter_app do
        api_key = app_store_connect_api_key(
            key_id: "#{ENV['APP_STORE_CONNECT_KEY_ID']}",
            issuer_id: "#{ENV['APP_STORE_CONNECT_ISSUER_ID']}",
            key_content: "#{ENV['APP_STORE_CONNECT_API_KEY']}",
            is_key_content_base64: true
        )
        app_store_connect_api_key(api_key: api_key)
        match(type: "appstore", api_key: api_key)
        pilot(api_key: api_key, skip_waiting_for_build_processing: true)
    end
end