// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoPE9S8jXtL5tHPdsDNZseRbr07jV9VAM',
    appId: '1:133839090627:web:5d19c780f20b4f21e1c376',
    messagingSenderId: '133839090627',
    projectId: 'raver-1fec4',
    authDomain: 'raver-1fec4.firebaseapp.com',
    storageBucket: 'raver-1fec4.appspot.com',
    measurementId: 'G-EWR90F10GE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIYNLmu3013gTkq3rjmY2p2lnp-l5oN2I',
    appId: '1:133839090627:android:5650eff7cde98623e1c376',
    messagingSenderId: '133839090627',
    projectId: 'raver-1fec4',
    storageBucket: 'raver-1fec4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1iQ2EFscnd8ocsttiAvg7zERYrZc8lyM',
    appId: '1:133839090627:ios:a3711f920bbf5246e1c376',
    messagingSenderId: '133839090627',
    projectId: 'raver-1fec4',
    storageBucket: 'raver-1fec4.appspot.com',
    androidClientId: '133839090627-3vrcaoj7s27mteo7crlb86ugd52h1l16.apps.googleusercontent.com',
    iosClientId: '133839090627-7g5e0li6omfire9666p5863ooa0dheen.apps.googleusercontent.com',
    iosBundleId: 'com.raverteam.tonight',
  );
}
