name: Flutter Monorepo CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Cache Flutter SDK
        uses: actions/cache@v2
        with:
          path: ${{ env.FLUTTER_HOME }}
          key: ${{ runner.os }}-flutter-sdk-${{ env.FLUTTER_VERSION }}-${{ hashFiles('.github/workflows/deploy_flutter_app.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-sdk-${{ env.FLUTTER_VERSION }}-

      - name: Install melos
        run: dart pub global activate melos

      - name: Add melos to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Bootstrap melos
        run: melos bootstrap

      - name: Run melos analyze
        run: melos run analyze

      - name: Run melos test
        run: melos run test